Repository CORE-GATECH-GROUP/serpent-tools, pull requests merged in 2018-04, with the labels that each got.

#107 Formatted labels for depleted material plots; DepletionReader plot method
  docs/api/depletion.rst
  docs/examples/DepletionReader.rst
  docs/examples/images/DepletionReader_22_0.png
  docs/examples/images/DepletionReader_23_0.png
  docs/examples/images/DepletionReader_25_0.png
  docs/welcome/changelog.rst
  examples/DepletionReader.ipynb
  examples/Detector.rst
  serpentTools/objects/materials.py
  serpentTools/parsers/depletion.py
  serpentTools/plot.py
  serpentTools/samplers/depletion.py
Labels: documentation, reader

#120 Proper x units for SampledDepletedMaterial
  docs/welcome/changelog.rst
  serpentTools/objects/materials.py
  serpentTools/samplers/depletion.py
Labels: bug

#121 Extra warnings and input checking for samplers
  serpentTools/samplers/__init__.py
Labels: bug

#122 Detector autolabel and format plot data
  serpentTools/objects/containers.py
  serpentTools/samplers/detector.py
Labels: enhancement

#95 Add xsplot output reader
  .travis.yml
  docs/api/xsplot.rst
  docs/examples/XSPlot.rst
  docs/examples/index.rst
  examples/Branching.ipynb
  examples/Detector.ipynb
  examples/XSPlot.ipynb
  examples/XSPlot_files/XSPlot_11_0.png
  examples/XSPlot_files/XSPlot_15_0.png
  examples/XSPlot_files/XSPlot_15_1.png
  examples/XSPlot_files/XSPlot_8_0.png
  serpentTools/objects/xsdata.py
  serpentTools/parsers/__init__.py
  serpentTools/parsers/xsplot.py
  serpentTools/tests/plut_xs0.m
  serpentTools/tests/test_xsplot.py
Labels: reader
