Repository CORE-GATECH-GROUP/serpent-tools, pull requests merged in 2018-02, with the labels that each got.

#87 Better indexing internals for DepletedMaterial object
  serpentTools/objects/materials.py
Labels: pythonicness

#88 Pre/post check methods
  serpentTools/objects/readers.py
  serpentTools/parsers/branching.py
  serpentTools/parsers/depletion.py
  serpentTools/parsers/detector.py
Labels: pythonicness, reader

#89 Added versioning/releasing information to docs
  README.rst
  docs/conf.py
  docs/develop/contributing.rst
  docs/develop/documentation.rst
  docs/develop/git.rst
  docs/develop/index.rst
  docs/serpentTools.pdf
  docs/welcome/about.rst
  setup.py
Labels: documentation

#90 [Documentation] Configuration for readthedocs
  docs/conf.py
Labels: documentation

#92 Fixed small bug where depletion reader missed materials in precheck
  serpentTools/parsers/depletion.py
Labels: bug, reader
