Repository CORE-GATECH-GROUP/serpent-tools, pull requests merged in 2018-05, with the labels that each got.

#135 [Docs] Developer guide for converting notebooks to rst;
  .gitattributes
  docs/api/containers.rst
  docs/api/index.rst
  docs/api/plot.rst
  docs/develop/codestyle.rst
  docs/develop/documentation.rst
  docs/develop/git.rst
  docs/develop/index.rst
  docs/develop/magicPlotOpts.rst
  docs/develop/plots.rst
  docs/magicPlotDoc.py
  serpentTools/objects/xsdata.py
  serpentTools/plot.py
Labels: documentation

#136 [Docs] Remove characters from conf.py that broke latexpdf build
  docs/conf.py
  docs/examples/images/DepletionReader_22_0.png
  docs/examples/images/DepletionReader_23_0.png
  docs/examples/images/DepletionReader_25_0.png
  docs/examples/images/Detector_38_0.png
  docs/examples/images/XSPlot_files/XSPlot_11_0.png
  docs/examples/images/XSPlot_files/XSPlot_15_1.png
  docs/examples/images/XSPlot_files/XSPlot_8_0.png
  docs/welcome/changelog.rst
Labels: bug, documentation

#131 Added beta_eff, lamba, and six FF to variables.yaml
  docs/variableGroups.rst
  docs/variableGroupsTop.rst
  docs/welcome/changelog.rst
  serpentTools/variables.yaml
Labels: documentation, support

#141 Reshape scatter mats
  docs/defaultSettings.rst
  docs/welcome/changelog.rst
  serpentTools/objects/containers.py
  serpentTools/parsers/branching.py
  serpentTools/settings.py
  serpentTools/tests/test_container.py
Labels: Work in progress, enhancement, support

#142 Add version at which changes from PR#114 will fully phase in
  docs/welcome/changelog.rst
  serpentTools/parsers/branching.py
Labels: release

#145 Add implicit truth methods for HomogUniv objects
  serpentTools/objects/containers.py
  serpentTools/tests/test_container.py
Labels: support

#148 [DOC] Fix README rendering; Update nb to rst conversion guide
  .github/pull_request_template.md
  README.rst
  docs/develop/documentation.rst
  docs/index.rst
Labels: documentation

#149 [ENH] Implement the sensitivity reader
  docs/api/index.rst
  docs/api/plot.rst
  docs/api/sensitivity.rst
  docs/changelog.rst
  docs/develop/plots.rst
  docs/examples/Sensitivity.rst
  docs/examples/Sensitivity_files/Sensitivity_20_0.png
  docs/examples/Sensitivity_files/Sensitivity_22_0.png
  docs/examples/Sensitivity_files/Sensitivity_24_0.png
  docs/examples/Sensitivity_files/Sensitivity_25_0.png
  docs/examples/index.rst
  examples/Branching.ipynb
  examples/DepletionReader.ipynb
  examples/Detector.ipynb
  examples/ResultsReader.ipynb
  examples/Sensitivity.ipynb
  examples/Settings.ipynb
  examples/XSPlot.ipynb
  examples/flattop_sens.m
  serpentTools/parsers/__init__.py
  serpentTools/parsers/sensitivity.py
  serpentTools/plot.py
  serpentTools/settings.py
  serpentTools/tests/bwr_sens0.m
  serpentTools/tests/test_sensivity.py
Labels: enhancement, reader

#154 [BUG] HomogUniv store number of groups as ints
  serpentTools/objects/containers.py
  serpentTools/tests/test_container.py
Labels: bug

#157 [BUG] Reshape scatter matrices using fortran ordering
  serpentTools/objects/containers.py
  serpentTools/tests/test_container.py
Labels: bug

#161 [API] Add utils module
  docs/api/index.rst
  docs/api/utils.rst
  docs/changelog.rst
  docs/rstVariableSets.py
  serpentTools/objects/__init__.py
  serpentTools/objects/containers.py
  serpentTools/objects/materials.py
  serpentTools/objects/xsdata.py
  serpentTools/parsers/branching.py
  serpentTools/parsers/history.py
  serpentTools/parsers/results.py
  serpentTools/parsers/sensitivity.py
  serpentTools/tests/__init__.py
  serpentTools/tests/test_container.py
  serpentTools/tests/test_sensivity.py
  serpentTools/tests/test_utils.py
  serpentTools/utils.py
Labels: API - Compatible, enhancement

#163 [STY] Custom notebook template for rst files
  docs/develop/documentation.rst
  docs/examples/Branching.rst
  docs/examples/DepletionReader.rst
  docs/examples/Detector.rst
  docs/examples/ResultsReader.rst
  docs/examples/Sensitivity.rst
  docs/examples/Settings.rst
  docs/examples/XSPlot.rst
  examples/Settings.ipynb
  examples/rstTemplate.tpl
Labels: documentation

#156 [ENH] Micro XS Reader Implemented
  docs/api/index.rst
  docs/api/microxs.rst
  docs/defaultSettings.rst
  docs/examples/MicroXSReader.rst
  docs/examples/index.rst
  examples/MicroXSReader.ipynb
  examples/ref_mdx0.m
  serpentTools/parsers/__init__.py
  serpentTools/parsers/microxs.py
  serpentTools/settings.py
  serpentTools/tests/ref_mdx0.m
  serpentTools/tests/ref_mdx0_noXS.m
  serpentTools/tests/test_microxs.py
Labels: API - Compatible, enhancement, reader

#164 [DOC] Use inheritance to show methods on public objects
  docs/api/containers.rst
  docs/api/depletion.rst
  docs/conf.py
  docs/examples/DepletionReader.rst
  docs/examples/Detector.rst
  serpentTools/objects/containers.py
  serpentTools/objects/materials.py
  serpentTools/parsers/depletion.py
  serpentTools/parsers/sensitivity.py
Labels: documentation

#165 [API] Implement HomogUniv plot method
  docs/changelog.rst
  docs/examples/Branching.rst
  docs/examples/Branching_files/Branching_32_1.png
  docs/examples/Branching_files/Branching_33_0.png
  docs/examples/ResultsReader.rst
  docs/examples/ResultsReader_files/ResultsReader_24_1.png
  docs/examples/ResultsReader_files/ResultsReader_50_1.png
  docs/examples/ResultsReader_files/ResultsReader_52_1.png
  docs/examples/ResultsReader_files/ResultsReader_55_0.png
  docs/examples/images/ResultsReader_24_1.png
  docs/examples/images/ResultsReader_51_1.png
  docs/examples/images/ResultsReader_53_1.png
  examples/Branching.ipynb
  examples/ResultsReader.ipynb
  serpentTools/objects/containers.py
  serpentTools/plot.py
Labels: API - Compatible, enhancement

#173 [DOC] Include git-based version in conf.py
  docs/conf.py
Labels: documentation, release

#174 [ENH] Add BaseObject and basic compare method
  serpentTools/messages.py
  serpentTools/objects/__init__.py
  serpentTools/objects/containers.py
  serpentTools/objects/readers.py
Labels: enhancement - comparisons

#175 [BUG] Point to importable directory in conf.py
  docs/conf.py
Labels: bug, documentation

#180 [API] Use zai for depletion getValues and plotting
  docs/changelog.rst
  docs/examples/DepletionReader.rst
  docs/examples/DepletionReader_files/DepletionReader_22_0.png
  docs/examples/DepletionReader_files/DepletionReader_23_0.png
  docs/examples/DepletionReader_files/DepletionReader_24_0.png
  docs/examples/DepletionReader_files/DepletionReader_25_0.png
  docs/examples/DepletionReader_files/DepletionReader_26_0.png
  examples/DepletionReader.ipynb
  serpentTools/objects/materials.py
  serpentTools/parsers/depletion.py
  serpentTools/tests/test_depletion.py
Labels: API - Compatible, reader, support

#182 [ENH] Better axis-labeling for depletion plots
  docs/examples/DepletionReader.rst
  docs/examples/DepletionReader_files/DepletionReader_23_0.png
  docs/examples/DepletionReader_files/DepletionReader_24_0.png
  docs/examples/DepletionReader_files/DepletionReader_26_0.png
  examples/DepletionReader.ipynb
  serpentTools/objects/materials.py
  serpentTools/parsers/depletion.py
  serpentTools/plot.py
  serpentTools/samplers/depletion.py
Labels: API - Compatible, enhancement

#183 [DOC] Add overview of supported files and readers
  docs/api/sampler.rst
  docs/conf.py
  docs/examples/Detector.rst
  docs/examples/MicroXSReader.rst
  docs/examples/ResultsReader.rst
  docs/examples/Sensitivity.rst
  docs/examples/XSPlot.rst
  docs/index.rst
  docs/overview.rst
Labels: documentation
