Repository CORE-GATECH-GROUP/serpent-tools, pull requests merged in 2020-05, with the labels that each got.

#400 DEV New data model and proposal for 0.10.0
  docs/develop/datamodel.rst
  docs/develop/documentation.rst
  docs/develop/index.rst
  docs/develop/old-data-model.rst
Labels: developer, discussion

#402 API Plot labels for XSData object; Other cleanups
  docs/examples/XSPlot.rst
  docs/examples/images/XSPlot_files/XSPlot_14_0.png
  docs/examples/images/XSPlot_files/XSPlot_15_0.png
  docs/examples/images/XSPlot_files/XSPlot_22_0.png
  examples/XSPlot.ipynb
  serpentTools/objects/xsdata.py
  serpentTools/parsers/xsplot.py
  tests/__init__.py
  tests/test_pt_xsplot.py
Labels: API - Compatible, documentation

#404 DEV Mark .m files as vendored for github linguist
  .gitattributes
Labels: developer

#405 Update sensitivity.py
  serpentTools/parsers/sensitivity.py
Labels: API - Compatible, enhancement

#406 REL Release 0.9.3
  docs/changelog.rst
  docs/conf.py
  docs/contributors.rst
  docs/develop/index.rst
  docs/index.rst
  docs/publications.rst
  serpentTools/__init__.py
  serpentTools/parsers/sensitivity.py
  setup.py
Labels: documentation, release

#407 DOC Update the main readme, release guide
  README.rst
  docs/develop/git.rst
  docs/glossary.rst
  setup.py
Labels: developer, documentation

#408 DEV Merge 0.9.3 into develop
  .gitattributes
  README.rst
  data/plut_xs0.m
  docs/_templates/myclass.rst
  docs/changelog.rst
  docs/conf.py
  docs/containers.rst
  docs/contributors.rst
  docs/develop/datamodel.rst
  docs/develop/documentation.rst
  docs/develop/git.rst
  docs/develop/index.rst
  docs/develop/old-data-model.rst
  docs/examples/DepletionReader.rst
  docs/examples/Detector.rst
  docs/examples/ResultsReader.rst
  docs/examples/XSPlot.rst
  docs/examples/images/XSPlot_files/XSPlot_14_0.png
  docs/examples/images/XSPlot_files/XSPlot_15_0.png
  docs/examples/images/XSPlot_files/XSPlot_22_0.png
  docs/glossary.rst
  docs/index.rst
  docs/publications.rst
  docs/requirements.txt
  examples/BranchToNodalDiffusion.ipynb
  examples/Branching.ipynb
  examples/DepletionMatrix.ipynb
  examples/DepletionReader.ipynb
  examples/Detector.ipynb
  examples/MicroXSReader.ipynb
  examples/ResultsReader.ipynb
  examples/Sensitivity.ipynb
  examples/Settings.ipynb
  examples/XSPlot.ipynb
  serpentTools/detectors.py
  serpentTools/objects/containers.py
  serpentTools/objects/materials.py
  serpentTools/objects/xsdata.py
  serpentTools/parsers/base.py
  serpentTools/parsers/branching.py
  serpentTools/parsers/bumat.py
  serpentTools/parsers/depletion.py
  serpentTools/parsers/detector.py
  serpentTools/parsers/history.py
  serpentTools/parsers/results.py
  serpentTools/parsers/sensitivity.py
  serpentTools/parsers/xsplot.py
  serpentTools/samplers/depletion.py
  serpentTools/samplers/detector.py
  tests/__init__.py
  tests/compare/test_depletion.py
  tests/test_ResultsReader.py
  tests/test_branching.py
  tests/test_depletion.py
  tests/test_detector.py
  tests/test_history.py
  tests/test_pt_depletion.py
  tests/test_pt_xsplot.py
  tests/test_xsplot.py
Labels: developer, release
